version: "3.3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - /opt/dockervol/jenkins:/var/jenkins_home 
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
      
   portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" 
    ports:
      - "9000:9000"
    container_name: portainer
  
